import { Jobs } from "../types/JobPost";

export const somejobs: Jobs[] = [
  {
    user_id: "e12345",
    name: "Tech Innovators Ltd.",
    cover: "https://example.com/cover1.jpg",
    logo_url: "https://example.com/logo1.png",
    image_url: "https://example.com/image1.jpg",
    product_count: 56,
    is_following: true,
    follower_count: 1200,
    activity_sector: "Technology",
    description:
      "Tech Innovators Ltd. is a leading company in the technology sector, specializing in innovative solutions for businesses. We provide cutting-edge software, hardware, and consulting services.",
  },
  {
    user_id: "e12346",
    name: "Green Earth Solutions",
    cover: "https://example.com/cover2.jpg",
    logo_url: "https://example.com/logo2.png",
    image_url: "https://example.com/image2.jpg",
    product_count: 32,
    is_following: false,
    follower_count: 800,
    activity_sector: "Environmental Services",
    description:
      "Green Earth Solutions focuses on providing sustainable and eco-friendly alternatives to traditional industrial practices. We are committed to protecting the environment while delivering high-quality services.",
  },
  {
    user_id: "e12347",
    name: "Urban Development Corp.",
    cover: "https://example.com/cover3.jpg",
    logo_url: "https://example.com/logo3.png",
    image_url: "https://example.com/image3.jpg",
    product_count: 120,
    is_following: true,
    follower_count: 5000,
    activity_sector: "Construction & Real Estate",
    description:
      "Urban Development Corp. is a leading construction company specializing in residential and commercial projects. We aim to build modern, sustainable, and affordable spaces for all.",
  },
  {
    user_id: "e12348",
    name: "Digital Marketing Experts",
    cover: "https://example.com/cover4.jpg",
    logo_url: "https://example.com/logo4.png",
    image_url: "https://example.com/image4.jpg",
    product_count: 10,
    is_following: true,
    follower_count: 450,
    activity_sector: "Marketing & Advertising",
    description:
      "Digital Marketing Experts offers innovative strategies to boost your online presence. We provide SEO, SEM, and social media management to help businesses grow and reach their target audience.",
  },
  {
    user_id: "e12349",
    name: "Innovative Design Studios",
    cover: "https://example.com/cover5.jpg",
    logo_url: "https://example.com/logo5.png",
    image_url: "https://example.com/image5.jpg",
    product_count: 20,
    is_following: false,
    follower_count: 320,
    activity_sector: "Design & Branding",
    description:
      "Innovative Design Studios is a creative agency that helps businesses develop strong brand identities. Our services include logo design, branding, and digital art creation.",
  },
  {
    user_id: "e12350",
    name: "Healthy Life Foods",
    cover: "https://example.com/cover6.jpg",
    logo_url: "https://example.com/logo6.png",
    image_url: "https://example.com/image6.jpg",
    product_count: 150,
    is_following: true,
    follower_count: 2500,
    activity_sector: "Food & Beverage",
    description:
      "Healthy Life Foods offers organic and healthy food options for individuals and families. Our products are fresh, locally sourced, and free from preservatives.",
  },
  {
    user_id: "e12351",
    name: "Techie Gadgets Store",
    cover: "https://example.com/cover7.jpg",
    logo_url: "https://example.com/logo7.png",
    image_url: "https://example.com/image7.jpg",
    product_count: 500,
    is_following: true,
    follower_count: 8000,
    activity_sector: "Retail & Electronics",
    description:
      "Techie Gadgets Store is your one-stop shop for the latest gadgets and electronic devices. We offer a wide range of products including smartphones, laptops, and wearables.",
  },
  {
    user_id: "e12352",
    name: "Global Travel Agency",
    cover: "https://example.com/cover8.jpg",
    logo_url: "https://example.com/logo8.png",
    image_url: "https://example.com/image8.jpg",
    product_count: 18,
    is_following: false,
    follower_count: 1500,
    activity_sector: "Travel & Tourism",
    description:
      "Global Travel Agency provides personalized travel packages for individuals and groups. We specialize in international travel, tours, and bespoke vacation experiences.",
  },
  {
    user_id: "e12353",
    name: "Creative Photography",
    cover: "https://example.com/cover9.jpg",
    logo_url: "https://example.com/logo9.png",
    image_url: "https://example.com/image9.jpg",
    product_count: 5,
    is_following: true,
    follower_count: 1200,
    activity_sector: "Photography & Videography",
    description:
      "Creative Photography is a professional photography and videography studio. We specialize in portraits, events, and commercial shoots, delivering high-quality results.",
  },
  {
    user_id: "e12354",
    name: "Fitness Hub",
    cover: "https://example.com/cover10.jpg",
    logo_url: "https://example.com/logo10.png",
    image_url: "https://example.com/image10.jpg",
    product_count: 75,
    is_following: false,
    follower_count: 500,
    activity_sector: "Health & Fitness",
    description:
      "Fitness Hub is a health and fitness company offering a wide range of fitness programs, equipment, and personal training. We strive to help people lead healthier, more active lives.",
  },
];
